# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohammad Sadegh Majidi Yazdi
title: Graduate Student - Computer Science
email: mmajidiy@purdue.edu
email_title: Email
# email: mmajidiy@purdue.edu
# email_title: Work Email
phone: +1 (765) 409-8314
# phone_title: Phone (Phone title override)
website: sadegh-majidi.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: sadegh-majidi
linkedin_username: mohammad-sadegh-majidi-yazdi-602275191
googlescholar_username: ZXFOus0AAAAJ

# Additional icon links
additional_links:
- title: CV
  icon: fa-regular fa-file
  url: assets/CV.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Mohammad Sadegh Majidi Yazdi, but I prefer to be called Sadegh. I am currently a first-year PhD student in the Department of Computer Science at <a href="https://www.purdue.edu/">Purdue University</a>. My current research focus is on the field of computer security, specifically security and privacy of LLMs (Large Language Models). I've got my B.Sc. degree in Computer Engineering at <a href="https://en.sharif.edu/">the Sharif University of Technology</a> (March 2024). My research interests are:
    - Computer Security
    - Large Language Models
    - Computer Architecture
    - Distributed Systems

  As a computer scientist, I have always enjoyed studying theoretical computer science and getting my hands dirty with mathematics, but I have a special fondness for the practical aspects of computer science. I love to spend consecutive hours trying to understand a challenge in the system security and solve it. My ultimate professional goal is to use my knowledge and skills to create something of value for the betterment of the world.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Purdue University
        caption: August 2024 - Present
        sub_title: PhD in Computer Science
        description: I'm in the middle of a challenging but rewarding academic journey at Purdue University, one of the top universities in the United States (it has the oldest Computer Science department in the country). During my PhD studies, I work there as a full-time research assistant. I am advised by <a href="https://mktrm.github.io/">Prof. Kazem Taram</a>.
      - layout: left
        title: Sharif University of Technology
        caption: September 2019 - March 2024
        sub_title: Bachelor of Science in Computer Engineering
        description: Pursuing a BSc in Computer Engineering at Sharif University of Technology, one of the premier institutions in the region. Achieved an outstanding GPA of 19.19/20, reflecting dedication and academic excellence.
      - layout: left
        title: Mandegar Alborz High School
        caption: Fall 2016 - Summer 2019
        sub_title: High School Diploma in Mathematics and Physics
        description: Completed high school education at Mandegar Alborz High School, one of the oldest and most prestigious institutions in Iran. Graduated with an outstanding GPA of 19.54/20, showcasing my academic prowess and commitment.

  - title: Research Experiences
    layout: list
    content:
      - layout: left
        title: Purdue University
        role: Research Assistant
        caption: Aug 2024 - Present
        description: I am currently working as a research assistant under the supervision of <a href="https://mktrm.github.io/">Prof. Kazem Taram</a> and as a full-time member of the SecArch Lab. Our lab's general focus is on the intersection of Computer Architecture and Security, but for now, I am focusing on the security and privacy of LLMs (Large Language Models), specifically investigating potential vulnerabilities related to inference process of these models. As the demand for inference is growing way faster than the training, we should consider the security risks of improving inference performance (latency & throughput) in our research. Understanding these risks is crucial for designing more secure and efficient AI systems.
      - layout: left
        title: Sharif University of Technology
        link: https://github.com/ARH80/WIDESim
        link_text: Github Repository
        additional_links:
          - title: Github Repository
            icon: fab fa-github
            url: https://github.com/ARH80/WIDESim
        role: Research Assistant
        caption: Feb 2023 - March 2024
        description: I worked for almost a year as a research assistant under the guidance of <a href="https://sharif.edu/~izadi/">Dr. Mohammad Izadi</a> and as a member of the Distributed and Multi-agent Systems Lab. We worked on WIDESim, a simulation tool for resource management and scheduling of workflows in distributed computing environments with graph topology. This tool was built upon the well-known <a href="https://github.com/Cloudslab/cloudsim">CloudSim</a> simulator. The development is finished, and we finished the work on the paper recently.

  - title: Publications
    layout: list
    content:
      - layout: top-middle
        title: "WIDESim: A Toolkit for Simulating Resource Management Techniques Of Scientific Workflows in Distributed Environments with Graph Topology"
        link: https://doi.org/10.1007/s10723-024-09778-y
        link_text: publication link
        caption: Journal of Grid Computing, August 2024
        description: Mohammad Amin Rayej, Hajar Siar, Ahmadreza Hamzei, Mohammad Sadegh Majidi Yazdi, Parsa Mohammadian, Mohammad Izadi

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Secure Messaging Application
        additional_links:
          - title:  Github Link
            icon: fab fa-github
            url: https://github.com/sadegh-majidi/Network_Security_Project
        description: Designed and Implemented a messaging application using Python as part of the Data & Network Security course. To satisfy a wide range of security measurements, we used a simplified version of the Double Ratchet algorithm and public-private key encryption and concepts like hashing and signing. This project is also well-structured in regard to software development standards.
      - layout: top-middle
        title: UEFI Weather Application
        additional_links:
          - title:  Github Link
            icon: fab fa-github
            url: https://github.com/Sharif-University-ESRLab/Fall2023-uefi-weather-app
        description: This project is part of the Hardware Lab course, featuring a UEFI application designed to display weather information and forecasts for users. The primary focus lies in the ability to interact with a network interface card (NIC) within the UEFI environment and initiate a simple HTTP request using the tools provided by EDK II, the standard UEFI implementation. This project serves as an excellent learning opportunity for working with the fundamentals of the UEFI environment and stands as a valuable reference for those seeking to utilize network interfaces within this setting.
      - layout: top-middle
        title: System Design Final Project
        additional_links:
          - title: Gitlab Link
            icon: fab fa-github
            url: https://gitlab.com/sadegh.majidi/tahlil-final-project
        description: Designed and implemented an online storage drive, similar to Google Drive, using Flask and Jinja templates, with additional use of JavaScript, HTML, and CSS. This drive supports file sharing, metadata storage, folder management, and various file manipulation operations, among other features. Additionally, implemented a full CI/CD pipeline for the project using GitLab Runner.
      - layout: top-middle
        title: Tweet Categorization NLP Project
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/sadegh-majidi/nlp_tweet_categorization
        description: Implemented a tweet categorization nlp model in C/C++ efficiently to achieve higher performance and speed and lesser resource usage. This model categorizes tweets based on their contents.
      - layout: top-middle
        title: CMinus Compiler
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/sadegh-majidi/compiler-project
        description: Implemented a Compiler for CMinus Langauge, a simplified subset of the C language, using Python and its standard libraries. The compiler consisted of Lexer, Parser, Code Generator, and Semantic Analyzer.
      - layout: top-middle
        title: MIPS Simulator
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/sadegh-majidi/MIPS-Processor
        description: Implemented a simplified MIPS processor simulator using Verilog. It supports pipeline and caching.
      - layout: top-middle
        title: SnappFood Minus
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/sadegh-majidi/Mobile-Programming-Final-Project
        description: An online food ordering and delivery app on Android.
      - layout: top-middle
        title: Online Shop Application
        additional_links:
          - title: Github Link
            icon: fab fa-github
            url: https://github.com/AdvProg2020/Project_team-5
        description: Designed and Implemented a simplified online shop as part of the Advanced Programming course using mainly Java and based on MVC architecture.

  - title: Technical Experiences
    layout: list
    content:
      - layout: left
        title: Yektanet
        link: https://www.yektanet.com
        link_text: Website
        role: Software Engineer
        caption: Feb 2021 - Oct 2021 & Oct 2022 - Apr 2023
        description: Yektanet is the largest online advertising company in Iran. As a backend software engineer, I designed and developed online affiliate marketing platform (<a href="https://chavosh.org/">Chavosh</a>) and product retargeting services using Django, Typescript, Postgresql and redis.
      - layout: left
        title: Gharar
        link: https://gharar.ir
        link_text: Website
        role: Software Engineer
        caption: Jun 2022 - Aug 2022
        description: As a full-stack software engineer, I developed a new chat system (backend & frontend) for webinars using Django, React, and Lua and I also reduced live streaming latency by properly using HLS protocol over Nginx.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in Computer Security, Computer Architecture, and Distributed Systems, some of my other interests and hobbies are:
      - Gaming, with a particular fondness for Role-Playing Games
      - Swimming, my favorite sport
      - Listening to music, especially in the Rock and Metal genre

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
